# Generated by Django 5.0.7 on 2024-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_commentmodel_ratingmodel'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='recipe.recipemodel'),
        ),
    ]
