# Generated by Django 5.0.7 on 2024-07-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofilemodel_saved_recipes'),
        ('userprofile', '0002_userprofilemodel_saved_recipes_and_more'),
    ]

    operations = [
    ]
