# Generated by Django 5.0.7 on 2024-07-21 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('rating', models.FloatField(default=0.0)),
                ('cuisine', models.CharField(max_length=100)),
                ('time_to_cook', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecipeModel_chef', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
