# Generated by Django 5.0.7 on 2024-07-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='time_to_cook',
        ),
    ]
