# Generated by Django 5.0.7 on 2024-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipemodel_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='cuisine',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='food_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='time_to_cook',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
