# Generated by Django 5.0.7 on 2024-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipemodel_cuisine_recipemodel_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
