# Generated by Django 5.0.7 on 2024-07-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_commentmodel_ratingmodel'),
        ('recipe', '0007_remove_savedrecipemodel_saved_recipes_and_more'),
    ]

    operations = [
    ]
