# Generated by Django 5.0.7 on 2024-07-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipemodel_ingredients'),
        ('recipe', '0007_remove_savedrecipemodel_saved_recipes_and_more'),
    ]

    operations = [
    ]
