# Generated by Django 5.0.7 on 2024-07-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_merge_20240727_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
