# Generated by Django 5.0.7 on 2024-07-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(default='No comment'),
        ),
    ]
