# Generated by Django 5.0.7 on 2024-07-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_remove_commentmodel_content_commentmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
